config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do 
    post "/archive", to: "articles#toggle_archive"
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Archive
    has_many :comments, dependent: :delete_all
    validates :title, :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    include Archive
    belongs_to :article
    validates :author, :body, presence: true
end

app/models/concerns/Archive.rb
module Archive
    extend ActiveSupport::Concern
    VALID_STATUSES = ['public', 'private', 'archived']

    included do 
        validates :status, allow_nil: true, inclusion: { in: VALID_STATUSES }
    end

    def archived?
        status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'rafael', password: 'adel', only: :destroy
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save 
      redirect_to @article
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params) 
      redirect_to @article
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle_archive 
    @article = Article.find(params[:article_id])
    new_status = @article.archived? ? 'public' : 'archived'
    if @article.update!(status: new_status)
      redirect_to @article
    else 
      render json: :show, status: :unprocessable_entity
    end
  end

  def destroy 
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create 
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comments_params)
        redirect_to @article
    end



    private
    def comments_params
        params.require(:comment).permit(:author, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <% article.errors.full_messages_for(:status).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<html>
    <body>
        <h3>Edit Article</h3>

        <%= render "form", article: @article %>
    </body>
</html>

app/views/articles/index.html.erb
<h1>Hello World!</h1>

<ul>
  <% @articles.each do |article| %>
      <li>
        <%= link_to "#{article.title}" , article %> - <%= link_to "edit", edit_article_path(article) %> - <%= link_to "delete", article, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %> <%= (" - archived" if article.archived?) %>
      </li>
  <% end %>
</ul>
<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<html>
    <body>
        <h3>New Article</h3>

        <%= render "form", article: @article %>
    </body>
</html>

app/views/articles/show.html.erb
<h1>Article</h1>

<h4><%= @article.title %></h4>

<p><%= @article.body %></p>

<p>You have <%= @article.comments.count %> comment(s)</p>
<%= render 'comments/form', article: @article %>
    
<%= render @article.comments %>

<div><%= link_to @article.archived? ? "unarchive" : "archive", article_archive_path(@article), data: { turbo_method: :post, turbo_confirm: "Are you sure?" } %></div>
<div><%= link_to "all", articles_path%></div>

app/views/comments/_comment.html.erb
<p><%= comment.author %>: <%= comment.body %></p> <%= (" - archived" if comment.archived?) %>

app/views/comments/_form.html.erb
<%= form_with model: [article, article.comments.build] do |form| %>
    <p>
        <%= form.label :author %>
        <%= form.text_field :author %>
    </p>
    <p>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>